package responsekeytype

var variantLabels = [...]string{
	Invalid:               "Invalid",
	Success:               "Success",
	Error:                 "Error",
	Message:               "Message",
	Data:                  "Data",
	Code:                  "Code",
	Valid:                 "Valid",
	Errors:                "Errors",
	Cached:                "Cached",
	Phase:                 "Phase",
	Reason:                "Reason",
	Total:                 "Total",
	Agents:                "Agents",
	Actions:               "Actions",
	Logs:                  "Logs",
	Snapshots:             "Snapshots",
	Sql:                   "Sql",
	Params:                "Params",
	Sets:                  "Sets",
	Plugins:               "Plugins",
	Tables:                "Tables",
	Settings:              "Settings",
	Providers:             "Providers",
	Dependencies:          "Dependencies",
	Rows:                  "Rows",
	Bytes:                 "Bytes",
	Size:                  "Size",
	FileSize:              "FileSize",
	Path:                  "Path",
	Filename:              "Filename",
	Checksum:              "Checksum",
	Duration:              "Duration",
	Count:                 "Count",
	Files:                 "Files",
	Directory:             "Directory",
	Scope:                 "Scope",
	Exported:              "Exported",
	Entry:                 "Entry",
	Computed:              "Computed",
	Removed:               "Removed",
	Limit:                 "Limit",
	Offset:                "Offset",
	Posts:                  "Posts",
	Categories:            "Categories",
	Category:              "Category",
	Export:                 "Export",
	Incrementals:          "Incrementals",
	TotalSize:             "TotalSize",
	Applied:               "Applied",
	Folder:                "Folder",
	SnapshotId:            "SnapshotId",
	Sequence:              "Sequence",
	FolderName:            "FolderName",
	TablesChanged:         "TablesChanged",
	TotalRows:             "TotalRows",
	TotalNewRows:          "TotalNewRows",
	ZipPath:               "ZipPath",
	ZipSize:               "ZipSize",
	BackupId:              "BackupId",
	ZipFailed:             "ZipFailed",
	SkipAudit:             "SkipAudit",
	TablesRestored:        "TablesRestored",
	DeletedByPolicy:       "DeletedByPolicy",
	DeletedOrphans:        "DeletedOrphans",
	DeletedFailed:         "DeletedFailed",
	SpaceFreedBytes:       "SpaceFreedBytes",
	Retention:             "Retention",
	Orphans:               "Orphans",
	Stuck:                 "Stuck",
	DryRun:                "DryRun",
	BytesFreed:            "BytesFreed",
	Deleted:               "Deleted",
	Cleaned:               "Cleaned",
	Activated:             "Activated",
	Deactivated:           "Deactivated",
	PluginSlug:            "Plugin Slug",
	IsUpdate:              "Is Update",
	IsSelfUpdate:          "Is Self Update",
	PluginVersion:         "Plugin Version",
	ActivationError:       "Activation Error",
	Inventory:             "Inventory",
	PluginFile:            "Plugin File",
	SelfUpdateStatus:      "Self Update Status",
	RollbackReason:        "Rollback Reason",
	RollbackAttempted:     "Rollback Attempted",
	RollbackSuccess:       "Rollback Success",
	RestoredVersion:       "Restored Version",
	RootCause:             "Root Cause",
	Validation:            "Validation",
	HealthCheck:           "Health Check",
	Passed:                "Passed",
	ErrorCount:            "Error Count",
	Healthy:               "Healthy",
	IssueCount:            "Issue Count",
	Issues:                "Issues",
	BootErrors:            "Boot Errors",
	Slug:                  "Slug",
	Title:                 "Title",
	Type:                  "Type",
	Action:                "Action",
	Status:                "Status",
	Percent:               "Percent",
	Plugin:                "Plugin",
	ErrorLog:              "Error Log",
	InfoLog:               "Info Log",
	FullLog:               "Full Log",
	StacktraceLog:         "Stacktrace Log",
	Exists:                "Exists",
	Content:               "Content",
	Truncated:             "Truncated",
	Lines:                 "Lines",
	TotalLines:            "Total Lines",
	RequestedAt:           "Requested At",
	ConfirmationRequired:  "Confirmation Required",
	ConfirmEndpoint:       "Confirm Endpoint",
	ExpiresIn:             "Expires In",
	DedupRegistry:         "Dedup Registry",
	EntryCount:            "Entry Count",
	Entries:               "Entries",
	FileSizeBytes:         "File Size Bytes",
	Ids:                   "Ids",
	TotalSnapshots:        "Total Snapshots",
	TotalSizeBytes:        "Total Size Bytes",
	TempFile:              "Temp File",
	Stmt:                  "Stmt",
	Columns:               "Columns",
	CreatedAt:             "Created At",
	UpdatedAt:             "Updated At",
	Timestamp:             "Timestamp",
	ParentTable:           "Parent Table",
	ChildTable:            "Child Table",
	FkColumn:              "FK Column",
	RefColumn:             "Ref Column",
	SeedOrder:             "Seed Order",
	TableCount:            "Table Count",
	DepCount:              "Dep Count",
	NewRows:               "New Rows",
	PluginDetails:         "Plugin Details",
	IncludedIds:           "Included Ids",
	IncrementalCount:      "Incremental Count",
	DetectionMethod:       "Detection Method",
	SqliteVersion:         "SQLite Version",
	IsCore:                "Is Core",
	ScheduleEnabled:       "Schedule Enabled",
	NextScheduledSnapshot: "Next Scheduled Snapshot",
	NextCleanup:           "Next Cleanup",
	RetentionType:         "Retention Type",
	RetentionDays:         "Retention Days",
	RetentionCount:        "Retention Count",
	SnapshotType:          "Snapshot Type",
	ErrorCategory:         "Error Category",
	LogHint:               "Log Hint",
	FilesUpdated:          "Files Updated",
	FilesDeleted:          "Files Deleted",
	FilesIgnored:          "Files Ignored",
	IgnoredFiles:          "Ignored Files",
	PluginZip:             "Plugin Zip",
	ResolvedUrl:           "Resolved Url",
	TraceLines:            "Trace Lines",
	CompletedAt:           "Completed At",
	ExportedAt:            "Exported At",
	Format:                "Format",
	FormatVersion:         "Format Version",
	JobId:                 "Job Id",
	TotalTables:           "Total Tables",
	TablesExported:        "Tables Exported",
	PoolSize:              "Pool Size",
	TotalBatches:          "Total Batches",
	CurrentBatch:          "Current Batch",
	TableProgress:         "Table Progress",
	IncrementalsApplied:   "Incrementals Applied",
	SkippedMaster:         "Skipped Master",
	ExportedTables:        "Exported Tables",
	SnapshotDir:           "Snapshot Dir",
	DirName:               "Dir Name",
	RowCount:              "Row Count",
	TriggeredBy:           "Triggered By",
	AuditData:             "Audit Data",
	LogDataKey:            "Log Data Key",
	OriginalId:            "Original Id",
	OriginalCreatedAt:     "Original Created At",
	SourceSite:            "Source Site",
	OriginalTitle:         "Original Title",
	OriginalType:          "Original Type",
	WpVersion:             "WP Version",
	PhpVersion:            "PHP Version",
	MysqlVersion:          "MySQL Version",
	SiteUrl:               "Site Url",
	DbPrefix:              "DB Prefix",
	PluginCount:           "Plugin Count",
	DurationMs:            "Duration Ms",
	TableCounts:           "Table Counts",
	DownloadUrl:           "Download Url",
	FileCount:             "File Count",
	GeneratedAt:           "Generated At",
	CacheStats:            "Cache Stats",
	FromCache:             "From Cache",
	TotalTransactions:     "Total Transactions",
	ByAction:              "By Action",
	ByStatus:              "By Status",
	Last24h:               "Last 24h",
	IncludePlugins:        "Include Plugins",
	PluginSelection:       "Plugin Selection",
	Compression:           "Compression",
	Async:                 "Async",
	Trigger:               "Trigger",
	MasterSnapshotId:      "Master Snapshot Id",
	MasterDir:             "Master Dir",
	Confirm:               "Confirm",
	CreateBackup:          "Create Backup",
	RequireBackup:         "Require Backup",
	Mode:                  "Mode",
	Frequency:             "Frequency",
	Time:                  "Time",
	Day:                   "Day",
	Scheduled:             "Scheduled",
	Trace:                 "Trace",
	Options:               "Options",
	TotalSizeFormatted:    "Total Size Formatted",
	OldestTimestamp:       "Oldest Timestamp",
	NewestTimestamp:        "Newest Timestamp",
	DiskFreeBytes:         "Disk Free Bytes",
	DiskFreeFormatted:     "Disk Free Formatted",
	SnapshotsCount:        "Snapshots Count",
	BytesFormatted:        "Bytes Formatted",
	IsSuccess:             "Is Success",
	HasAnyErrors:          "Has Any Errors",
	Details:               "Details",
	Order:                 "Order",
	Graph:                 "Graph",
	InDegree:              "In Degree",
	Manifest:              "Manifest",
	SqlitePath:            "SQLite Path",
	RealPath:              "Real Path",
	FilePath:              "File Path",
	PkColumn:              "PK Column",
	TableName:             "Table Name",
	Id:                    "Id",
	Name:                  "Name",
	Available:             "Available",
	Capabilities:          "Capabilities",
	Version:               "Version",
	Author:                "Author",
	Description:           "Description",
	Active:                "Active",
	TotalFiles:            "Total Files",
	LastSeenId:            "Last Seen Id",
	FileType:              "File Type",
	Provider:              "Provider",
	Snapshot:              "Snapshot",
	Source:                "Source",
	FullSite:              "Full Site",
	DatabaseOnly:          "Database Only",
	Selective:             "Selective",
	Restore:               "Restore",
	Import:                "Import",
	Strict:                "Strict",
	ApplyIncrementals:     "Apply Incrementals",
	Sqlite:                "SQLite",
	SqliteFile:            "SQLite File",
	InternalMode:          "Internal Mode",
	OpcacheAvailable:      "OPcache Available",
	OpcacheReset:          "OPcache Reset",
	FilesInvalidated:      "Files Invalidated",
	Zip:                   "Zip",
	ZipFile:               "Zip File",
	ChecksumMd5:           "Checksum MD5",
	PluginName:            "Plugin Name",
	Route:                 "Route",
	Methods:               "Methods",
	Result:                "Result",
	Results:               "Results",
	Account:               "Account",
	AccountId:             "Account Id",
	AccountLabel:          "Account Label",
	Accounts:              "Accounts",
	ConnectionStatus:      "Connection Status",
	RemotePath:            "Remote Path",
	RemoteUrl:             "Remote Url",
	ProviderSettings:      "Provider Settings",
	RotationApplied:       "Rotation Applied",
	CurrentCount:          "Current Count",
	CurrentSizeMB:         "Current Size MB",
	MaxCount:              "Max Count",
	MaxSizeMB:             "Max Size MB",
	IsOverLimit:           "Is Over Limit",
	OAuthState:            "OAuth State",
	OAuthUrl:              "OAuth Url",
	Backup:                "Backup",
	BackupHistory:         "Backup History",
	BaseFullBackupId:      "Base Full Backup Id",
	UploadResult:          "Upload Result",
	DeletedFiles:          "Deleted Files",
	FilesMoved:            "Files Moved",
	MovedFiles:            "Moved Files",
	ArchiveFileSizeBytes:  "Archive File Size Bytes",
	AppPassword:           "App Password",
	DisplayName:           "Display Name",
	Email:                 "Email",
	Username:              "Username",
	UserId:                "User Id",
	Users:                 "Users",
	Uuid:                  "UUID",
	Role:                  "Role",
	Revoked:               "Revoked",
	TokenMask:             "Token Mask",
	ReassignedTo:          "Reassigned To",
	BranchName:            "Branch Name",
	Branches:              "Branches",
	CommitSha:             "Commit SHA",
	Repositories:          "Repositories",
	Created:               "Created",
	Updated:               "Updated",
	Skipped:               "Skipped",
	Meta:                  "Meta",
	Pagination:            "Pagination",
	NextAction:            "Next Action",
	FieldsModified:        "Fields Modified",
	File:                  "File",
	LogFile:               "Log File",
	ErrorFile:             "Error File",
	StacktraceFile:        "Stacktrace File",
	ArchiveCount:          "Archive Count",
	SizeBytes:             "Size Bytes",
	LastModified:          "Last Modified",
	LineCount:             "Line Count",
	IncludeInfoLog:        "Include Info Log",
	IncludeErrorLog:       "Include Error Log",
	IncludeStacktrace:     "Include Stacktrace",
	MaxLines:              "Max Lines",
	Database:              "Database",
	TransactionCount:      "Transaction Count",
	ErrorSessionCount:     "Error Session Count",
	Cleared:               "Cleared",
	ClearedBy:             "Cleared By",
	Machine:               "Machine",
	Ip:                    "Ip",
	ActivityLog:           "Activity Log",
	ErrorSessions:         "Error Sessions",
	Rotation:              "Rotation",
	Config:                "Config",
	OldestArchive:         "Oldest Archive",
	NewestArchive:         "Newest Archive",
	Riseup:                "Riseup",
	Qupload:               "QUpload",
	Namespace:             "Namespace",
	TotalRoutes:           "Total Routes",
	Routes:                "Routes",
	Pattern:               "Pattern",
	Api:                   "Api",
	DbAvailable:           "DB Available",
	MemoryLimit:           "Memory Limit",
	PostMaxSize:           "Post Max Size",
	PostMaxSizeBytes:      "Post Max Size Bytes",
	PreviousVersion:       "Previous Version",
	RolledBack:            "Rolled Back",
	ServerTime:            "Server Time",
	UploadMaxFilesize:     "Upload Max Filesize",
	UploadMaxFilesizeBytes: "Upload Max Filesize Bytes",
}
