#!/usr/bin/env python3
"""
35-db-struct-enum-generator.py — Inspects Go model structs and auto-generates type-safe column enums
in a dedicated enums/ package with standard gofmt tab-aligned formatting.

Usage:
  python 03-ai-scripts/35-db-struct-enum-generator.py --dir 04-code/golang/pkg/models
  python 03-ai-scripts/35-db-struct-enum-generator.py --file 04-code/golang/pkg/models/item.go
  python 03-ai-scripts/35-db-struct-enum-generator.py --file 04-code/golang/pkg/models/item.go --out-dir 04-code/golang/pkg/generated/item
  python 03-ai-scripts/35-db-struct-enum-generator.py --dry-run
"""

from __future__ import annotations

import argparse
from importlib import import_module
from pathlib import Path
import re
import subprocess
import sys

sys.path.insert(0, str(Path(__file__).parent))
engine = import_module("02-shared-engine")

ExitCodeType = engine.ExitCodeType

STRUCT_PATTERN = re.compile(r"type\s+([A-Z][A-Za-z0-9_]+)\s+struct\s*\{([^}]+)\}", re.MULTILINE)
FIELD_PATTERN = re.compile(r"^\s*([A-Za-z0-9_]+)\s+([A-Za-z0-9_\[\]*]+)(?:\s+`([^`]+)`)?", re.MULTILINE)
PACKAGE_PATTERN = re.compile(r"package\s+([A-Za-z0-9_]+)")
MODULE_PATTERN = re.compile(r"^\s*module\s+([^\s]+)", re.MULTILINE)


def to_snake_case(name: str) -> str:
    s = re.sub(r'(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', s).lower()


def parse_structs_from_file(file_path: Path) -> tuple[str, list[dict]]:
    content = file_path.read_text(encoding="utf-8", errors="replace")
    pkg_match = PACKAGE_PATTERN.search(content)
    pkg_name = pkg_match.group(1) if pkg_match else "models"

    structs = []
    for match in STRUCT_PATTERN.finditer(content):
        struct_name = match.group(1)
        if struct_name.endswith(("DbRegistry", "DbRepo", "Repository", "Registry", "Connection", "Wrapper", "Scanner", "Executor")):
            continue
        body = match.group(2)
        # Skip connection wrapper structs
        if "*sql.DB" in body or "*dbengine.DbWrapper" in body or "sql.DB" in body:
            continue

        fields = []
        for f_match in FIELD_PATTERN.finditer(body):
            field_name = f_match.group(1)
            field_type = f_match.group(2)
            tags = f_match.group(3) or ""

            # Check if public field and not embedded
            if field_name[0].isupper() and not field_name.startswith("XXX_"):
                col_match = re.search(r'db:"([^"]+)"', tags)
                col_name = col_match.group(1) if col_match else field_name
                fields.append({
                    "name": field_name,
                    "type": field_type,
                    "tags": tags,
                    "column": col_name,
                })

        if fields:
            start_pos = match.start()
            end_pos = match.end()
            struct_code = content[start_pos:end_pos]
            structs.append({
                "name": struct_name,
                "fields": fields,
                "code": struct_code,
                "source_file": file_path.name,
            })

    return pkg_name, structs


def get_scan_helper(field_type: str, pkg_qual: str = "dbengine.") -> str:
    ft = field_type.strip("*")
    if ft == "string":
        return f"{pkg_qual}ScanString"
    if ft in ("int", "int32"):
        return f"{pkg_qual}ScanInt"
    if ft == "int64":
        return f"{pkg_qual}ScanInt64"
    if ft in ("uint64", "uint"):
        return f"{pkg_qual}ScanUint64"
    if ft in ("uint32", "uint16", "uint8"):
        return f"{pkg_qual}ScanUint"
    if ft == "bool":
        return f"{pkg_qual}ScanBool"
    if ft in ("float64", "float32"):
        return f"{pkg_qual}ScanFloat64"
    return f"{pkg_qual}ScanString"


def generate_enums_for_struct(struct_info: dict) -> str:
    s_name = struct_info["name"]
    enum_type = f"{s_name}FieldType"
    reg_type = f"{s_name[0].lower() + s_name[1:]}DbRegistry"
    valid_map = f"{s_name[0].lower() + s_name[1:]}ValidMap"
    db_var = f"{s_name}Db"
    field_var = f"{s_name}Field"
    short_name = s_name[:-6] if s_name.endswith("Record") else s_name
    has_alias = short_name != s_name

    lines = [
        "// Code generated by db struct enum generator. DO NOT EDIT.",
        "",
        "package enums",
        "",
        "import (",
        '\t"encoding/json"',
        '\t"fmt"',
        "",
        '\t"coding-guidelines/common/pkg/appfault"',
        '\t"coding-guidelines/common/pkg/errtype"',
        ")",
        "",
        f"// {enum_type} represents column name enums for {s_name}.",
        f"type {enum_type} string",
        "",
        f"// Name returns the identifier name of the field enum.",
        f"func (e {enum_type}) Name() string {{",
        "\treturn string(e)",
        "}",
        "",
        f"// String returns the string representation of the field enum.",
        f"func (e {enum_type}) String() string {{",
        "\treturn string(e)",
        "}",
        "",
        f"// Value returns the raw string value of the field enum.",
        f"func (e {enum_type}) Value() string {{",
        "\treturn string(e)",
        "}",
        "",
        f"// IsCompare checks equality against another field enum object.",
        f"func (e {enum_type}) IsCompare(target {enum_type}) bool {{",
        "\treturn e == target",
        "}",
        "",
        f"// IsEnum checks whether this field enum exists in the valid enum map.",
        f"func (e {enum_type}) IsEnum() bool {{",
        f"\treturn {valid_map}[e]",
        "}",
        "",
        f"// MarshalJSON implements json.Marshaler.",
        f"func (e {enum_type}) MarshalJSON() ([]byte, error) {{",
        "\treturn json.Marshal(string(e))",
        "}",
        "",
        f"// UnmarshalJSON implements json.Unmarshaler with strict map validation.",
        f"func (e *{enum_type}) UnmarshalJSON(data []byte) error {{",
        "\tvar s string",
        "\tif err := json.Unmarshal(data, &s); err != nil {",
        "\t\treturn err",
        "\t}",
        f"\ttarget := {enum_type}(s)",
        f"\tif !{valid_map}[target] {{",
        f'\t\treturn fmt.Errorf("invalid %s enum: %s", "{enum_type}", s)',
        "\t}",
        "\t*e = target",
        "\treturn nil",
        "}",
        "",
        f"// ToJSON converts the field enum to a JSON string representation, returning an AppError on failure.",
        f"func (e {enum_type}) ToJSON() (string, *appfault.AppError) {{",
        "\tb, err := json.Marshal(string(e))",
        "\tif err != nil {",
        '\t\treturn "", appfault.Wrap(errtype.Serialization, err, "serialize field to json")',
        "\t}",
        "\treturn string(b), nil",
        "}",
        "",
        f"// FromJSON parses a field enum from a JSON string representation, returning an AppError on failure.",
        f"func (e *{enum_type}) FromJSON(s string) *appfault.AppError {{",
        "\tvar str string",
        "\tif err := json.Unmarshal([]byte(s), &str); err != nil {",
        '\t\treturn appfault.Wrap(errtype.Serialization, err, "deserialize field from json")',
        "\t}",
        f"\ttarget := {enum_type}(str)",
        f"\tif !{valid_map}[target] {{",
        f'\t\treturn appfault.New(errtype.Validation, fmt.Sprintf("invalid %s enum: %s", "{enum_type}", str))',
        "\t}",
        "\t*e = target",
        "\treturn nil",
        "}",
        "",
    ]

    for f in struct_info["fields"]:
        f_name = f["name"]
        lines.extend([
            f"// Is{f_name} checks whether this field enum instance is {f_name}.",
            f"func (e {enum_type}) Is{f_name}() bool {{",
            f"\treturn e == {db_var}.{f_name}",
            "}",
            "",
        ])

    lines.append(f"type {reg_type} struct {{")
    for f in struct_info["fields"]:
        lines.append(f"\t{f['name']} {enum_type}")
    lines.append("}")
    lines.append("")

    lines.extend([
        f"// All returns a slice of all field enums in {s_name}.",
        f"func (r {reg_type}) All() []{enum_type} {{",
        f"\treturn []{enum_type}{{",
    ])
    for f in struct_info["fields"]:
        lines.append(f"\t\tr.{f['name']},")
    lines.extend([
        "\t}",
        "}",
        "",
        f"// Names returns a slice of string names for all fields in {s_name}.",
        f"func (r {reg_type}) Names() []string {{",
        "\treturn []string{",
    ])
    for f in struct_info["fields"]:
        col_name = f.get("column", f["name"])
        lines.append(f'\t\t"{col_name}",')
    lines.extend([
        "\t}",
        "}",
        "",
        f"// IsEnum checks whether the target object matches any registered field enum in {s_name}.",
        f"func (r {reg_type}) IsEnum(target {enum_type}) bool {{",
        f"\treturn {valid_map}[target]",
        "}",
        "",
    ])

    for f in struct_info["fields"]:
        f_name = f["name"]
        lines.extend([
            f"// Is{f_name} checks whether the target object is {f_name}.",
            f"func (r {reg_type}) Is{f_name}(target {enum_type}) bool {{",
            f"\treturn target == r.{f_name}",
            "}",
            "",
        ])

    lines.extend([
        f"// ToJSON converts the field registry to a JSON string representation, returning an AppError on failure.",
        f"func (r {reg_type}) ToJSON() (string, *appfault.AppError) {{",
        "\tb, err := json.Marshal(r)",
        "\tif err != nil {",
        '\t\treturn "", appfault.Wrap(errtype.Serialization, err, "serialize registry to json")',
        "\t}",
        "\treturn string(b), nil",
        "}",
        "",
    ])

    lines.append(f"// {db_var} provides scoped access to field enums: {db_var}.<Field>.")
    lines.append(f"var {db_var} = {reg_type}{{")
    for f in struct_info["fields"]:
        f_name = f["name"]
        col_name = f.get("column", f_name)
        lines.append(f'\t{f_name}: "{col_name}",')
    lines.append("}")
    lines.append("")

    lines.append(f"// {valid_map} provides O(1) map validation for field enums.")
    lines.append(f"var {valid_map} = map[{enum_type}]bool{{")
    for f in struct_info["fields"]:
        f_name = f["name"]
        lines.append(f"\t{db_var}.{f_name}: true,")
    lines.append("}")
    lines.append("")

    lines.append(f"// {field_var} is an alias to {db_var}.")
    lines.append(f"var {field_var} = {db_var}")
    lines.append("")

    if has_alias:
        lines.extend([
            f"// {short_name}Db is an alias to {db_var} for concise business usage.",
            f"var {short_name}Db = {db_var}",
            "",
            f"// {short_name}Field is an alias to {field_var} for concise business usage.",
            f"var {short_name}Field = {field_var}",
            "",
        ])

    return "\n".join(lines)


def generate_enum_consts_content(structs: list[dict]) -> str:
    lines = [
        "// Code generated by db struct enum generator. DO NOT EDIT.",
        "",
        "package enums",
        "",
        "// Canonical table name constants.",
        "const (",
    ]
    for s in structs:
        s_name = s["name"]
        short_name = s_name[:-6] if s_name.endswith("Record") else s_name
        lines.append(f'\t{s_name}Table = "{s_name}"')
        if short_name != s_name:
            lines.append(f"\t{short_name}Table = {s_name}Table")
    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def generate_parent_consts_content(pkg_name: str, structs: list[dict], enums_pkg_import: str) -> str:
    lines = [
        "// Code generated by db struct enum generator. DO NOT EDIT.",
        "",
        f"package {pkg_name}",
        "",
        "import (",
        '\t"coding-guidelines/common/pkg/dbengine"',
        f'\t"{enums_pkg_import}"',
        ")",
        "",
        "// Canonical table name constants re-exported from enums package.",
        "const (",
    ]
    for s in structs:
        s_name = s["name"]
        short_name = s_name[:-6] if s_name.endswith("Record") else s_name
        lines.append(f"\t{s_name}Table = enums.{s_name}Table")
        if short_name != s_name:
            lines.append(f"\t{short_name}Table = enums.{short_name}Table")
    lines.append(")")
    lines.append("")

    # Dedicated QueryBuilder type aliases
    lines.append("// Dedicated QueryBuilder type aliases.")
    lines.append("type (")
    for s in structs:
        s_name = s["name"]
        enum_type = f"enums.{s_name}FieldType"
        qb_type = f"{s_name}QueryBuilder"
        short_name = s_name[:-6] if s_name.endswith("Record") else s_name
        lines.append(f"\t// {qb_type} is the dedicated query builder for {s_name}.")
        lines.append(f"\t{qb_type} = dbengine.QueryBuilder[{s_name}, {enum_type}]")
        if short_name != s_name:
            short_qb_type = f"{short_name}QueryBuilder"
            lines.append(f"\t// {short_qb_type} is an alias to {qb_type} for concise business usage.")
            lines.append(f"\t{short_qb_type} = {qb_type}")
    lines.append(")")
    lines.append("")

    # Dedicated generic Repository type aliases
    lines.append("// Dedicated generic Repository type aliases.")
    lines.append("type (")
    for s in structs:
        s_name = s["name"]
        enum_type = f"enums.{s_name}FieldType"
        generic_repo_type = f"{s_name}Repository"
        short_name = s_name[:-6] if s_name.endswith("Record") else s_name
        lines.append(f"\t// {generic_repo_type} is the dedicated generic repository for {s_name}.")
        lines.append(f"\t{generic_repo_type} = dbengine.Repository[{s_name}, {enum_type}]")
        if short_name != s_name:
            short_generic_repo_type = f"{short_name}Repository"
            lines.append(f"\t// {short_generic_repo_type} is an alias to {generic_repo_type} for concise business usage.")
            lines.append(f"\t{short_generic_repo_type} = {generic_repo_type}")
    lines.append(")")
    lines.append("")

    # Re-export field enums and registries for backward compatibility
    lines.append("// Re-exported field enums and registries for backward compatibility.")
    lines.append("type (")
    for s in structs:
        s_name = s["name"]
        enum_type = f"{s_name}FieldType"
        lines.append(f"\t// {enum_type} aliases enums.{enum_type} for direct package access.")
        lines.append(f"\t{enum_type} = enums.{enum_type}")
    lines.append(")")
    lines.append("")

    lines.append("var (")
    for s in structs:
        s_name = s["name"]
        db_var = f"{s_name}Db"
        field_var = f"{s_name}Field"
        short_name = s_name[:-6] if s_name.endswith("Record") else s_name
        lines.append(f"\t// {db_var} aliases enums.{db_var}.")
        lines.append(f"\t{db_var} = enums.{db_var}")
        lines.append(f"\t// {field_var} aliases enums.{field_var}.")
        lines.append(f"\t{field_var} = enums.{field_var}")
        if short_name != s_name:
            lines.append(f"\t// {short_name}Db aliases enums.{short_name}Db.")
            lines.append(f"\t{short_name}Db = enums.{short_name}Db")
            lines.append(f"\t// {short_name}Field aliases enums.{short_name}Field.")
            lines.append(f"\t{short_name}Field = enums.{short_name}Field")
    lines.append(")")
    lines.append("")

    # Typed DbRepo aliases
    repo_aliases = []
    for s in structs:
        s_name = s["name"]
        short_name = s_name[:-6] if s_name.endswith("Record") else s_name
        if short_name != s_name:
            repo_type = f"{s_name}DbRepo"
            short_repo_type = f"{short_name}DbRepo"
            repo_aliases.append((short_repo_type, repo_type))

    if repo_aliases:
        lines.append("// Typed DbRepo aliases for concise business usage.")
        lines.append("type (")
        for short_repo_type, repo_type in repo_aliases:
            lines.append(f"\t// {short_repo_type} is an alias to {repo_type} for concise business usage.")
            lines.append(f"\t{short_repo_type} = {repo_type}")
        lines.append(")")
        lines.append("")

    return "\n".join(lines)


def find_primary_key(struct_info: dict) -> dict | None:
    s_name = struct_info["name"]
    for f in struct_info["fields"]:
        if f["name"].lower() == f"{s_name.lower()}id":
            return f
    for f in struct_info["fields"]:
        if f["name"].endswith("Id") or f["name"] in ("Id", "ID"):
            return f
    return None


def generate_repo_methods_for_struct(struct_info: dict, pkg_name: str, enums_pkg_import: str) -> str:
    s_name = struct_info["name"]
    enum_type = f"enums.{s_name}FieldType"
    db_var = f"enums.{s_name}Db"
    scan_func = f"Scan{s_name}"
    repo_type = f"{s_name}DbRepo"
    qb_type = f"{s_name}QueryBuilder"
    generic_repo_type = f"{s_name}Repository"
    table_const = f"enums.{s_name}Table"
    short_name = s_name[:-6] if s_name.endswith("Record") else s_name
    has_alias = short_name != s_name
    short_repo_type = f"{short_name}DbRepo"

    lines = []

    # Scanner function
    lines.append(f"// {scan_func} maps a database row scanner to a {s_name} entity.")
    lines.append(f"func {scan_func}(row dbengine.RowScanner) (*{s_name}, error) {{")
    lines.append(f"\tvar item {s_name}")
    lines.append("\tvar (")
    for f in struct_info["fields"]:
        lines.append(f"\t\traw_{f['name']} any")
    lines.append("\t)")
    lines.append("\terr := row.Scan(")
    for f in struct_info["fields"]:
        lines.append(f"\t\t&raw_{f['name']},")
    lines.append("\t)")
    lines.append("\tif err != nil {")
    lines.append("\t\treturn nil, err")
    lines.append("\t}")
    lines.append("")
    for f in struct_info["fields"]:
        helper = get_scan_helper(f["type"])
        lines.append(f"\titem.{f['name']} = {helper}(raw_{f['name']})")
    lines.append("\treturn &item, nil")
    lines.append("}")
    lines.append("")

    # Repository struct & methods
    lines.extend([
        f"// {repo_type} provides typed database repository access for {s_name}.",
        f"type {repo_type} struct {{",
        "\tdb   *dbengine.DbWrapper",
        f"\trepo *{generic_repo_type}",
        "}",
        "",
        f"// New{repo_type} initializes a typed repository for {s_name}.",
        f"func New{repo_type}(db *dbengine.DbWrapper) *{repo_type} {{",
        f"\trepo := dbengine.NewRepository[{s_name}, {enum_type}](",
        "\t\tdb,",
        f"\t\t{table_const},",
        f"\t\t{scan_func},",
        "\t)",
        f"\treturn &{repo_type}{{",
        "\t\tdb:   db,",
        "\t\trepo: repo,",
        "\t}",
        "}",
        "",
    ])

    if has_alias:
        lines.extend([
            f"// New{short_repo_type} is an alias constructor for {repo_type}.",
            f"func New{short_repo_type}(db *dbengine.DbWrapper) *{short_repo_type} {{",
            f"\treturn New{repo_type}(db)",
            "}",
            "",
        ])

    lines.extend([
        f"// Db returns the underlying DbWrapper.",
        f"func (r *{repo_type}) Db() *dbengine.DbWrapper {{",
        "\treturn r.db",
        "}",
        "",
        f"// Repo returns the underlying generic Repository.",
        f"func (r *{repo_type}) Repo() *{generic_repo_type} {{",
        "\treturn r.repo",
        "}",
        "",
        f"// Query returns a fluent QueryBuilder initialized with all standard fields projected.",
        f"func (r *{repo_type}) Query() *{qb_type} {{",
        f"\treturn r.repo.Query().Select({db_var}.All()...)",
        "}",
        "",
        f"// QueryBare returns a fluent QueryBuilder without any pre-selected fields.",
        f"func (r *{repo_type}) QueryBare() *{qb_type} {{",
        "\treturn r.repo.Query()",
        "}",
        "",
        f"// FindAll executes the query selecting all fields and returns a ListResult envelope.",
        f"func (r *{repo_type}) FindAll(ctx context.Context) dbengine.ListResult[{s_name}] {{",
        "\treturn r.Query().FindAll(ctx)",
        "}",
        "",
        f"// First executes the query selecting all fields and returns the first record in an EntityResult envelope.",
        f"func (r *{repo_type}) First(ctx context.Context) dbengine.EntityResult[{s_name}] {{",
        "\treturn r.Query().First(ctx)",
        "}",
        "",
        f"// Count returns the total number of records matching the query.",
        f"func (r *{repo_type}) Count(ctx context.Context) dbengine.Int64Result {{",
        "\treturn r.Query().Count(ctx)",
        "}",
        "",
    ])

    pk_field = find_primary_key(struct_info)
    all_fields = struct_info["fields"]
    cols = [f.get("column", f["name"]) for f in all_fields]
    cols_str = ", ".join(cols)
    placeholders = ", ".join(["?"] * len(cols))

    if pk_field:
        pk_name = pk_field["name"]
        insert_args = []
        for f in all_fields:
            if f["name"] == pk_name:
                insert_args.append("id")
            else:
                insert_args.append(f"item.{f['name']}")
        insert_args_str = ", ".join(insert_args)
        lines.extend([
            f"// Insert inserts a new {s_name} record into the database.",
            f"func (r *{repo_type}) Insert(ctx context.Context, item *{s_name}) dbengine.RowsAffectedResult {{",
            f'\tquery := "INSERT INTO {s_name} ({cols_str}) VALUES ({placeholders});"',
            f"\tvar id any = item.{pk_name}",
            f"\tif item.{pk_name} == 0 {{",
            "\t\tid = nil",
            "\t}",
            f"\treturn r.db.ExecRowsAffected(ctx, query, {insert_args_str})",
            "}",
            "",
        ])
    else:
        insert_args_str = ", ".join(f"item.{f['name']}" for f in all_fields)
        lines.extend([
            f"// Insert inserts a new {s_name} record into the database.",
            f"func (r *{repo_type}) Insert(ctx context.Context, item *{s_name}) dbengine.RowsAffectedResult {{",
            f'\tquery := "INSERT INTO {s_name} ({cols_str}) VALUES ({placeholders});"',
            f"\treturn r.db.ExecRowsAffected(ctx, query, {insert_args_str})",
            "}",
            "",
        ])

    if pk_field:
        pk_name = pk_field["name"]
        pk_col = pk_field.get("column", pk_name)
        non_pks = [f for f in all_fields if f["name"] != pk_name]
        if non_pks:
            set_clauses = ", ".join(f"{f.get('column', f['name'])} = ?" for f in non_pks)
            update_args_str = ", ".join(f"item.{f['name']}" for f in non_pks) + f", item.{pk_name}"
            lines.extend([
                f"// Update updates an existing {s_name} record identified by its primary key.",
                f"func (r *{repo_type}) Update(ctx context.Context, item *{s_name}) dbengine.RowsAffectedResult {{",
                f'\tquery := "UPDATE {s_name} SET {set_clauses} WHERE {pk_col} = ?;"',
                f"\treturn r.db.ExecRowsAffected(ctx, query, {update_args_str})",
                "}",
                "",
            ])
        else:
            lines.extend([
                f"// Update is a no-op for {s_name} containing only primary key.",
                f"func (r *{repo_type}) Update(ctx context.Context, item *{s_name}) dbengine.RowsAffectedResult {{",
                f"\treturn dbengine.SuccessRowsAffected(0)",
                "}",
                "",
            ])
    else:
        lines.extend([
            f"// Update is a no-op for {s_name} without primary key.",
            f"func (r *{repo_type}) Update(ctx context.Context, item *{s_name}) dbengine.RowsAffectedResult {{",
            f"\treturn dbengine.SuccessRowsAffected(0)",
            "}",
            "",
        ])

    if pk_field:
        lines.extend([
            f"// DeleteById deletes a {s_name} record by its primary key identifier.",
            f"func (r *{repo_type}) DeleteById(ctx context.Context, id uint64) dbengine.RowsAffectedResult {{",
            f"\treturn r.repo.DeleteBy(ctx, {db_var}.{pk_field['name']}, id)",
            "}",
            "",
        ])
    else:
        lines.extend([
            f"// DeleteById deletes a {s_name} record by identifier.",
            f"func (r *{repo_type}) DeleteById(ctx context.Context, id uint64) dbengine.RowsAffectedResult {{",
            f"\treturn r.repo.DeleteBy(ctx, {db_var}.All()[0], id)",
            "}",
            "",
        ])

    return "\n".join(lines)


def format_dir_with_gofmt(dir_path: Path):
    if not dir_path.is_dir():
        return
    for go_file in dir_path.glob("*.go"):
        subprocess.run(["gofmt", "-w", str(go_file)], check=False)


def find_go_module_root(start_dir: Path) -> tuple[Path, str] | None:
    curr = start_dir.resolve()
    for parent in [curr] + list(curr.parents):
        mod_file = parent / "go.mod"
        if mod_file.is_file():
            text = mod_file.read_text(encoding="utf-8", errors="replace")
            m = MODULE_PATTERN.search(text)
            if m:
                return parent, m.group(1).strip()
    return None


def get_enums_import_path(dest_dir: Path, repo_root: Path) -> str:
    mod_info = find_go_module_root(dest_dir)
    if mod_info is not None:
        mod_root, mod_name = mod_info
        try:
            rel = dest_dir.resolve().relative_to(mod_root).as_posix()
            return f"{mod_name}/{rel}/enums"
        except ValueError:
            pass
    return "enums"


def process_generation(target_dir: Path, out_dir_path: Path | None = None, dry_run: bool = False, specific_file: Path | None = None) -> bool:
    repo_root = Path(__file__).resolve().parent.parent

    # Determine structs to process
    all_structs = []
    pkg_name = "models"

    if specific_file is not None:
        p, structs = parse_structs_from_file(specific_file)
        if structs:
            pkg_name = p
            all_structs.extend(structs)
    else:
        for go_file in sorted(target_dir.glob("*.go")):
            if go_file.name.endswith("_test.go") or go_file.name.endswith("_gen.go") or go_file.name == "consts.go":
                continue
            p, structs = parse_structs_from_file(go_file)
            if structs:
                pkg_name = p
                all_structs.extend(structs)

    if not all_structs:
        print("No structs found to generate.")
        return False

    dest_dir = out_dir_path if out_dir_path is not None else target_dir
    enums_dir = dest_dir / "enums"
    enums_import = get_enums_import_path(dest_dir, repo_root)

    if dry_run:
        print(f"[DRY RUN] Would generate {len(all_structs)} structs into {dest_dir} and {enums_dir}")
        print(f"  Package: {pkg_name}, Enums import: {enums_import}")
        for s in all_structs:
            print(f"  - Struct: {s['name']} ({len(s['fields'])} fields)")
        return True

    dest_dir.mkdir(parents=True, exist_ok=True)
    enums_dir.mkdir(parents=True, exist_ok=True)

    # Clean legacy _gen.go files
    for legacy_file in dest_dir.glob("*_gen.go"):
        legacy_file.unlink()
    for legacy_file in enums_dir.glob("*_gen.go"):
        legacy_file.unlink()

    # 1. Generate enums/consts.go
    enum_consts_file = enums_dir / "consts.go"
    enum_consts_content = generate_enum_consts_content(all_structs)
    enum_consts_file.write_text(enum_consts_content, encoding="utf-8")
    print(f"  ✔ Generated {enum_consts_file}")

    # 2. Generate each enum file in enums/<snake_name>.go
    for s in all_structs:
        s_snake = to_snake_case(s["name"])
        enum_file = enums_dir / f"{s_snake}.go"
        enum_content = generate_enums_for_struct(s)
        enum_file.write_text(enum_content, encoding="utf-8")
        print(f"  ✔ Generated {enum_file}")

    # 3. Generate parent consts.go
    parent_consts_file = dest_dir / "consts.go"
    parent_consts_content = generate_parent_consts_content(pkg_name, all_structs, enums_import)
    parent_consts_file.write_text(parent_consts_content, encoding="utf-8")
    print(f"  ✔ Generated {parent_consts_file}")

    # 4. Generate model & repo files in dest_dir
    for s in all_structs:
        s_name = s["name"]
        s_snake = to_snake_case(s_name)
        def_file = dest_dir / f"{s_snake}.go"
        source_file = s.get("source_file", "")

        # When models are defined in a separate models.go file, avoid duplicating struct definition
        struct_code_block = "" if source_file == "models.go" else f"{s['code']}\n\n"

        header = f"""// Code generated by db struct enum generator. DO NOT EDIT.

package {pkg_name}

import (
\t"context"

\t"coding-guidelines/common/pkg/dbengine"
\t"{enums_import}"
)

{struct_code_block}"""
        repo_code = generate_repo_methods_for_struct(s, pkg_name, enums_import)
        def_file.write_text(header + repo_code + "\n", encoding="utf-8")
        print(f"  ✔ Generated {def_file}")

    # 5. Format all generated directories with gofmt
    format_dir_with_gofmt(enums_dir)
    format_dir_with_gofmt(dest_dir)
    print(f"  ✔ Formatted all files with gofmt")

    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate type-safe column name enums from Go model structs")
    parser.add_argument("--dir", help="Directory containing Go model files", default="")
    parser.add_argument("--file", help="Specific Go model file to parse", default="")
    parser.add_argument("--out-dir", help="Explicit output directory for generated files", default="")
    parser.add_argument("--dry-run", action="store_true", help="Preview output without writing files")

    args = parser.parse_args()
    repo_root = Path(__file__).resolve().parent.parent

    out_dir_path: Path | None = None
    if args.out_dir:
        out_dir_path = Path(args.out_dir)
        if not out_dir_path.is_absolute():
            out_dir_path = repo_root / out_dir_path

    if args.file:
        file_path = Path(args.file)
        if not file_path.is_absolute():
            file_path = repo_root / file_path
        if not file_path.is_file():
            print(f"Error: file not found: {file_path}", file=sys.stderr)
            return 1
        process_generation(file_path.parent, out_dir_path, args.dry_run, specific_file=file_path)
        return 0

    target_dir = Path(args.dir) if args.dir else repo_root / "04-code" / "golang" / "pkg" / "dbengine"
    if not target_dir.is_absolute():
        target_dir = repo_root / target_dir

    if not target_dir.is_dir():
        print(f"Error: directory not found: {target_dir}", file=sys.stderr)
        return 1

    process_generation(target_dir, out_dir_path, args.dry_run)
    print(f"Completed: processed database enums and repositories.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
