import { useState, useEffect, useCallback } from "react";
import { Progress } from "@/components/ui/progress";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { wsClient, WS_EVENTS } from "@/lib/ws";
import { Check, X, RefreshCw, AlertCircle, Copy, Upload } from "lucide-react";
import { cn } from "@/lib/utils";
import { LogViewer, LogEntry } from "@/components/shared/LogViewer";
import { toast } from "sonner";
import { SyncTreeView } from "@/components/plugins/SyncTreeView";
import { api } from "@/lib/api";
import type { FileChange } from "@/lib/api";

export enum SyncStageStatusType {
  Pending = "pending",
  Running = "running",
  Success = "success",
  Error = "error",
  Skipped = "skipped"
}

export interface SyncStage {
  name: string;
  label: string;
  status: SyncStageStatusType;
  message?: string;
}

interface SyncLogPayload {
  operationType: string;
  pluginId: number;
  siteId: number;
  log: LogEntry;
}

interface SyncProgressPayload {
  pluginId: number;
  siteId: number;
  progress: number;
  total: number;
  message: string;
}

interface SyncCompletePayload {
  pluginId: number;
  siteId: number;
  success: boolean;
  message?: string;
  error?: string;
  filesChecked?: number;
  filesModified?: number;
  localFiles?: number;
  remoteFiles?: number;
  added?: number;
  modified?: number;
  deleted?: number;
  changes?: FileChange[];
  inSync?: boolean;
}

interface SyncProgressDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  pluginName: string;
  siteName: string;
  pluginId: number;
  siteId: number;
  onComplete?: (success: boolean) => void;
}

const DEFAULT_STAGES: SyncStage[] = [
  { name: "init", label: "Initializing", status: SyncStageStatusType.Pending },
  { name: "fetch", label: "Fetching Remote Files", status: SyncStageStatusType.Pending },
  { name: "compare", label: "Comparing Files", status: SyncStageStatusType.Pending },
  { name: "report", label: "Generating Report", status: SyncStageStatusType.Pending },
];

function buildErrorReport(
  pluginName: string,
  siteName: string,
  pluginId: number,
  siteId: number,
  errorMessage: string,
  stages: SyncStage[],
  logs: LogEntry[]
): string {
  const timestamp = new Date().toISOString();
  const failedStage = stages.find(s => s.status === SyncStageStatusType.Error);
  
  const logSection = logs.length > 0 
    ? `### Execution Logs\n\`\`\`\n${logs.map(l => `[${l.timestamp}] [${l.level.toUpperCase()}] [${l.step}] ${l.message}`).join('\n')}\n\`\`\`\n`
    : "";
  
  return `## Sync Error Report

**App:** WP Plugin Publish
**Timestamp:** ${timestamp}

### Context
- **Plugin:** ${pluginName} (ID: ${pluginId})
- **Site:** ${siteName} (ID: ${siteId})
- **Failed Stage:** ${failedStage?.label || "Unknown"}

### Error Message
\`\`\`
${errorMessage}
\`\`\`

### Stage Status
${stages.map(s => `- ${s.label}: ${s.status}${s.message ? ` - ${s.message}` : ""}`).join("\n")}

${logSection}
---
*Generated by WP Plugin Publish Error Reporter*`;
}

export function SyncProgressDialog({
  open,
  onOpenChange,
  pluginName,
  siteName,
  pluginId,
  siteId,
  onComplete,
}: SyncProgressDialogProps) {
  const [stages, setStages] = useState<SyncStage[]>(DEFAULT_STAGES);
  const [overallProgress, setOverallProgress] = useState(0);
  const [isComplete, setIsComplete] = useState(false);
  const [isFail, setIsFail] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [syncResult, setSyncResult] = useState<{
    filesChecked?: number;
    filesModified?: number;
    localFiles?: number;
    remoteFiles?: number;
    added?: number;
    modified?: number;
    deleted?: number;
    changes?: FileChange[];
    inSync?: boolean;
  } | null>(null);

  // Reset state when dialog opens
  useEffect(() => {
    if (open) {
      setStages(DEFAULT_STAGES.map(s => ({ ...s, status: SyncStageStatusType.Pending })));
      setOverallProgress(0);
      setIsComplete(false);
      setIsFail(false);
      setErrorMessage(null);
      setLogs([]);
      setSyncResult(null);
    }
  }, [open]);

  // Listen for WebSocket events
  useEffect(() => {
    if (!open) return;

    // Handle sync started
    const unsubStarted = wsClient.on(WS_EVENTS.SYNC_STARTED, (data: unknown) => {
      const payload = data as { pluginId: number; siteId: number };
      if (payload.pluginId === pluginId && payload.siteId === siteId) {
        setStages(prev => prev.map(s => 
          s.name === "init" ? { ...s, status: SyncStageStatusType.Running } : s
        ));
        setLogs(prev => [...prev, {
          timestamp: new Date().toISOString(),
          level: 'info',
          step: 'init',
          message: `Starting sync for ${pluginName} with ${siteName}`,
        }]);
      }
    });

    // Handle sync progress
    const unsubProgress = wsClient.on(WS_EVENTS.SYNC_PROGRESS, (data: unknown) => {
      const payload = data as SyncProgressPayload;
      if (payload.pluginId === pluginId && payload.siteId === siteId) {
        const progress = payload.total > 0 ? Math.round((payload.progress / payload.total) * 100) : 0;
        setOverallProgress(progress);
        
        setLogs(prev => [...prev, {
          timestamp: new Date().toISOString(),
          level: 'info',
          step: 'compare',
          message: payload.message,
        }]);

        // Update stages based on progress
        setStages(prev => prev.map(s => {
          if (s.name === "init" && s.status === SyncStageStatusType.Running) return { ...s, status: SyncStageStatusType.Success };
          if (s.name === "fetch" && s.status === SyncStageStatusType.Pending) return { ...s, status: SyncStageStatusType.Success };
          if (s.name === "compare") return { ...s, status: SyncStageStatusType.Running, message: payload.message };
          return s;
        }));
      }
    });

    // Handle log events
    const unsubLog = wsClient.on(WS_EVENTS.LOG, (data: unknown) => {
      const payload = data as SyncLogPayload;
      if (payload.operationType === "sync" && payload.pluginId === pluginId && payload.siteId === siteId && payload.log) {
        setLogs(prev => [...prev, payload.log]);
        
        // Update stage based on log step
        const step = payload.log.step;
        setStages(prev => prev.map(s => {
          if (s.name === step) {
            let newStatus: SyncStageStatusType = SyncStageStatusType.Running;
            if (payload.log.level === "error") newStatus = SyncStageStatusType.Error;
            return { ...s, status: newStatus, message: payload.log.message };
          }
          return s;
        }));
      }
    });

    // Handle sync complete
    const unsubComplete = wsClient.on(WS_EVENTS.SYNC_COMPLETE, (data: unknown) => {
      const payload = data as SyncCompletePayload;
      if (payload.pluginId === pluginId && payload.siteId === siteId) {
        setIsComplete(true);
        setIsFail(!payload.success);
        setOverallProgress(100);
        setSyncResult({
          filesChecked: payload.filesChecked,
          filesModified: payload.filesModified,
          localFiles: payload.localFiles,
          remoteFiles: payload.remoteFiles,
          added: payload.added,
          modified: payload.modified,
          deleted: payload.deleted,
          changes: payload.changes,
          inSync: payload.inSync,
        });
        
        if (payload.error) {
          setErrorMessage(payload.error);
        }
        
        setLogs(prev => [...prev, {
          timestamp: new Date().toISOString(),
          level: payload.success ? 'info' : 'error',
          step: 'complete',
          message: payload.success 
            ? `Sync complete: ${payload.filesChecked || 0} files checked, ${payload.filesModified || 0} modified`
            : `Sync failed: ${payload.error || 'Unknown error'}`,
        }]);
        
        setStages(prev => prev.map(s => ({
          ...s,
          status: payload.success ? SyncStageStatusType.Success : (s.status === SyncStageStatusType.Running ? SyncStageStatusType.Error : s.status)
        })));

        onComplete?.(payload.success);
      }
    });

    return () => {
      unsubStarted();
      unsubProgress();
      unsubLog();
      unsubComplete();
    };
  }, [open, pluginId, siteId, pluginName, siteName, onComplete]);

  const getStageIcon = (stage: SyncStage) => {
    switch (stage.status) {
      case SyncStageStatusType.Success:
        return <Check className="h-4 w-4 text-primary" />;
      case SyncStageStatusType.Error:
        return <X className="h-4 w-4 text-destructive" />;
      case SyncStageStatusType.Running:
        return <div className="h-4 w-4 border-2 border-primary border-t-transparent rounded-full animate-spin" />;
      default:
        return <div className="h-4 w-4 rounded-full border-2 border-muted-foreground/30" />;
    }
  };

  const activeStageCount = stages.filter(s => s.status === SyncStageStatusType.Success || s.status === SyncStageStatusType.Running).length;
  const totalStages = stages.length;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-2xl max-h-[90vh] flex flex-col overflow-hidden">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <RefreshCw className="h-5 w-5 text-primary" />
            {isComplete ? (!isFail ? "Sync Complete" : "Sync Failed") : "Syncing..."}
          </DialogTitle>
          <DialogDescription>
            Checking <strong>{pluginName}</strong> against <strong>{siteName}</strong>
          </DialogDescription>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto space-y-4 py-4">
          {/* Overall Progress */}
          <div className="space-y-2">
            <div className="flex justify-between text-sm">
              <span className="text-muted-foreground">
                Stage {Math.min(activeStageCount + 1, totalStages)} of {totalStages}
              </span>
              <span className="font-medium">{Math.round(overallProgress)}%</span>
            </div>
            <Progress value={overallProgress} className="h-2" />
          </div>

          {/* Stage List */}
          <div className="space-y-2">
            {stages.map((stage) => (
              <div
                key={stage.name}
                className={cn(
                  "flex items-center gap-3 p-3 rounded-lg border transition-colors",
                  stage.status === SyncStageStatusType.Running && "border-primary bg-primary/5",
                  stage.status === SyncStageStatusType.Success && "border-primary/30 bg-primary/5",
                  stage.status === SyncStageStatusType.Error && "border-destructive bg-destructive/5",
                  stage.status === SyncStageStatusType.Pending && "border-border opacity-60"
                )}
              >
                {getStageIcon(stage)}
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium">{stage.label}</p>
                  {stage.message && (
                    <p className="text-xs text-muted-foreground truncate">
                      {stage.message}
                    </p>
                  )}
                </div>
                {stage.status === SyncStageStatusType.Success && (
                  <Badge variant="outline" className="text-xs text-primary border-primary/30">
                    Done
                  </Badge>
                )}
                {stage.status === SyncStageStatusType.Error && (
                  <Badge variant="outline" className="text-xs text-destructive border-destructive/30">
                    Failed
                  </Badge>
                )}
              </div>
            ))}
          </div>

          {/* Live Logs */}
          <LogViewer
            logs={logs}
            title="Sync Logs"
            height="h-32"
            emptyMessage="Waiting for sync to start..."
          />

          {/* Sync Tree View */}
          {isComplete && !isFail && syncResult && syncResult.changes && syncResult.changes.length > 0 && (
            <SyncTreeView
              changes={syncResult.changes}
              localFiles={syncResult.localFiles || 0}
              remoteFiles={syncResult.remoteFiles || 0}
              added={syncResult.added || 0}
              modified={syncResult.modified || 0}
              deleted={syncResult.deleted || 0}
              inSync={syncResult.inSync || false}
            />
          )}

          {/* In Sync Message */}
          {isComplete && !isFail && syncResult && (!syncResult.changes || syncResult.changes.length === 0) && (
            <SyncTreeView
              changes={[]}
              localFiles={syncResult.localFiles || syncResult.filesChecked || 0}
              remoteFiles={syncResult.remoteFiles || 0}
              added={0}
              modified={0}
              deleted={0}
              inSync={true}
            />
          )}

          {/* Error Message */}
          {isComplete && isFail && errorMessage && (
            <div className="rounded-lg border border-destructive/30 bg-destructive/5 p-4 space-y-3">
              <div className="flex items-start gap-2">
                <AlertCircle className="h-5 w-5 text-destructive mt-0.5 flex-shrink-0" />
                <div className="flex-1 min-w-0">
                  <p className="font-medium text-destructive">Sync Failed</p>
                  <p className="text-sm text-muted-foreground mt-1 break-words">{errorMessage}</p>
                </div>
              </div>
              
              <div className="flex gap-2 pt-2 border-t border-destructive/20">
                <Button
                  variant="outline"
                  size="sm"
                  className="text-xs"
                  onClick={() => {
                    const report = buildErrorReport(pluginName, siteName, pluginId, siteId, errorMessage, stages, logs);
                    navigator.clipboard.writeText(report);
                    toast.success("Error report copied to clipboard");
                  }}
                >
                  <Copy className="h-3 w-3 mr-1" />
                  Copy Error Report
                </Button>
              </div>
            </div>
          )}
        </div>

        <DialogFooter className="gap-2">
          {isComplete && !isFail && syncResult && syncResult.changes && syncResult.changes.length > 0 && (
            <Button
              variant="default"
              onClick={async () => {
                try {
                  toast.info("Pushing changes to remote...");
                  const res = await api.pushSync(pluginId, siteId);
                  if (res.data && !res.data.isFail && res.data.isSuccess) {
                    toast.success(`Sync pushed: ${res.data.filesUpdated} updated, ${res.data.filesDeleted} deleted`);
                  } else {
                    toast.error("Push failed: " + (res.data?.errorMessage || "Unknown error"));
                  }
                } catch (err: unknown) {
                  const message = err instanceof Error ? err.message : String(err);
                  toast.error("Push failed: " + message);
                }
              }}
            >
              <Upload className="h-4 w-4 mr-1" />
              Push Changes
            </Button>
          )}
          <Button
            variant={isComplete ? "outline" : "default"}
            onClick={() => onOpenChange(false)}
          >
            {isComplete ? "Close" : "Cancel"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
